"""JAX-based prototype modules for a grain-growth style ELLE rewrite."""

from .artifacts import dominant_grain_map, save_snapshot_artifacts, snapshot_statistics
from .benchmark_validation import (
    build_benchmark_validation_report,
    evaluate_release_dataset_benchmarks,
    evaluate_rasterized_grain_growth_benchmark,
    evaluate_static_grain_growth_benchmark,
    summarize_elle_label_components,
    summarize_sequence_trends,
    write_benchmark_validation_report,
)
from .calibration import (
    BEST_KNOWN_FINE_FOAM_CALIBRATED_PRESET,
    BEST_KNOWN_FINE_FOAM_PARAMS,
    BEST_KNOWN_FINE_FOAM_PRESET,
    BEST_KNOWN_FINE_FOAM_TRUTHFUL_MESH_PRESET,
    calibrate_fine_foam,
    generate_elle_seeded_candidate_sequence,
    score_existing_calibration_runs,
    write_calibration_report,
)
from .elle_export import extract_flynn_topology, write_unode_elle
from .fft_bridge import (
    FFTMechanicsSnapshot,
    FFTSnapshotPaths,
    apply_legacy_fft_snapshot_to_mesh_state,
    load_legacy_fft_snapshot,
    load_legacy_fft_snapshot_sequence,
)
from .faithful_config import FaithfulSeedData, FaithfulSolverConfig, load_faithful_seed
from .gbm_faithful import (
    FAITHFUL_GBM_DEFAULTS,
    FaithfulGBMSetup,
    build_faithful_gbm_setup,
    run_faithful_gbm_simulation,
)
from .legacy_reference import (
    build_legacy_reference_bundle,
    compare_legacy_reference_bundle,
    compare_legacy_reference_snapshot,
    compare_legacy_reference_transition,
    extract_legacy_reference_snapshot,
    extract_legacy_reference_transition,
    load_legacy_reference_bundle,
    write_legacy_reference_bundle,
)
from .mechanics_replay import (
    run_faithful_mechanics_replay,
    validate_faithful_mechanics_transition,
)
from .mobility import (
    FaithfulMobilityDB,
    PhaseBoundaryProperty,
    arrhenius_boundary_mobility,
    boundary_segment_mobility,
    caxis_misorientation_degrees,
    default_phase_db_path,
    get_phase_boundary_property,
    load_phase_boundary_db,
    misorientation_mobility_reduction,
)
from .nucleation import NucleationConfig, apply_nucleation_stage
from .recovery import RecoveryConfig, apply_recovery_stage
from .faithful_runtime import (
    initialize_faithful_order_parameters,
    run_faithful_simulation,
    run_faithful_simulation_with_topology,
)
from .elle_phasefield import (
    EllePhaseFieldTemplate,
    EllePhaseFieldConfig,
    initialize_elle_phasefield,
    load_elle_phasefield_state,
    phasefield_statistics,
    run_elle_phasefield_simulation,
    save_elle_phasefield_artifacts,
    write_elle_phasefield_state,
)
from .figure2_validation import (
    build_figure2_line_validation_report,
    collect_elle_label_area_distributions,
    summarize_elle_label_area_distribution,
    write_figure2_line_validation_html,
    write_figure2_line_validation_report,
)
from .elle_html_viewer import write_elle_html_viewer
from .elle_visualize import render_elle_file
from .phasefield_compare import (
    collect_elle_phasefield_snapshots,
    compare_elle_phasefield_files,
    compare_elle_phasefield_sequences,
    compare_elle_phasefield_states,
    inspect_elle_phasefield_binary,
    run_original_elle_phasefield_sequence,
    run_python_elle_phasefield_sequence,
    write_phasefield_comparison_report,
)
from .mesh import (
    MeshFeedbackConfig,
    MeshRelaxationConfig,
    apply_mesh_feedback,
    apply_mesh_transport,
    build_mesh_state,
    compute_mesh_motion_velocity,
    couple_mesh_to_order_parameters,
    load_elle_mesh_seed,
    mesh_motion_field,
    rasterize_mesh_labels,
    relax_mesh_state,
)
from .microstructure_validation import (
    collect_elle_microstructure_snapshots,
    compare_elle_microstructure_sequences,
    summarize_elle_microstructure,
    summarize_liu_suckale_datasets,
    write_microstructure_validation_report,
)
from .paper_validation import (
    assess_current_rewrite_against_papers,
    build_paper_validation_report,
    summarize_liu_suckale_paper,
    summarize_liu_suckale_paper_from_text,
    summarize_llorens_structure,
    summarize_llorens_structure_from_text,
    write_paper_validation_report,
)
from .simulation import (
    GrainGrowthConfig,
    initialize_order_parameters,
    load_elle_label_seed,
    run_mesh_only_simulation,
    run_simulation,
)
from .topology import TopologyTracker, run_simulation_with_topology

__all__ = [
    "GrainGrowthConfig",
    "MeshFeedbackConfig",
    "MeshRelaxationConfig",
    "TopologyTracker",
    "apply_mesh_feedback",
    "apply_mesh_transport",
    "apply_legacy_fft_snapshot_to_mesh_state",
    "assess_current_rewrite_against_papers",
    "build_benchmark_validation_report",
    "build_mesh_state",
    "build_paper_validation_report",
    "BEST_KNOWN_FINE_FOAM_CALIBRATED_PRESET",
    "BEST_KNOWN_FINE_FOAM_PARAMS",
    "BEST_KNOWN_FINE_FOAM_PRESET",
    "BEST_KNOWN_FINE_FOAM_TRUTHFUL_MESH_PRESET",
    "build_faithful_gbm_setup",
    "compare_legacy_reference_bundle",
    "compare_legacy_reference_snapshot",
    "compare_legacy_reference_transition",
    "calibrate_fine_foam",
    "collect_elle_phasefield_snapshots",
    "compare_elle_phasefield_files",
    "compare_elle_phasefield_sequences",
    "compare_elle_phasefield_states",
    "compare_elle_microstructure_sequences",
    "compute_mesh_motion_velocity",
    "collect_elle_microstructure_snapshots",
    "collect_elle_label_area_distributions",
    "couple_mesh_to_order_parameters",
    "dominant_grain_map",
    "EllePhaseFieldConfig",
    "EllePhaseFieldTemplate",
    "FAITHFUL_GBM_DEFAULTS",
    "FaithfulGBMSetup",
    "FFTMechanicsSnapshot",
    "FFTSnapshotPaths",
    "FaithfulSeedData",
    "FaithfulSolverConfig",
    "extract_flynn_topology",
    "extract_legacy_reference_snapshot",
    "extract_legacy_reference_transition",
    "evaluate_release_dataset_benchmarks",
    "evaluate_rasterized_grain_growth_benchmark",
    "evaluate_static_grain_growth_benchmark",
    "build_figure2_line_validation_report",
    "FaithfulMobilityDB",
    "generate_elle_seeded_candidate_sequence",
    "get_phase_boundary_property",
    "initialize_elle_phasefield",
    "initialize_faithful_order_parameters",
    "initialize_order_parameters",
    "inspect_elle_phasefield_binary",
    "load_elle_label_seed",
    "load_elle_mesh_seed",
    "load_elle_phasefield_state",
    "load_faithful_seed",
    "load_legacy_fft_snapshot",
    "load_legacy_fft_snapshot_sequence",
    "load_legacy_reference_bundle",
    "run_faithful_mechanics_replay",
    "mesh_motion_field",
    "misorientation_mobility_reduction",
    "NucleationConfig",
    "phasefield_statistics",
    "PhaseBoundaryProperty",
    "rasterize_mesh_labels",
    "RecoveryConfig",
    "render_elle_file",
    "relax_mesh_state",
    "default_phase_db_path",
    "load_phase_boundary_db",
    "run_faithful_gbm_simulation",
    "run_faithful_simulation",
    "run_faithful_simulation_with_topology",
    "run_mesh_only_simulation",
    "run_elle_phasefield_simulation",
    "run_original_elle_phasefield_sequence",
    "run_python_elle_phasefield_sequence",
    "run_simulation",
    "run_simulation_with_topology",
    "save_elle_phasefield_artifacts",
    "save_snapshot_artifacts",
    "score_existing_calibration_runs",
    "snapshot_statistics",
    "apply_recovery_stage",
    "apply_nucleation_stage",
    "build_legacy_reference_bundle",
    "boundary_segment_mobility",
    "arrhenius_boundary_mobility",
    "caxis_misorientation_degrees",
    "summarize_elle_microstructure",
    "summarize_elle_label_area_distribution",
    "summarize_elle_label_components",
    "summarize_liu_suckale_paper",
    "summarize_liu_suckale_paper_from_text",
    "summarize_liu_suckale_datasets",
    "summarize_llorens_structure",
    "summarize_llorens_structure_from_text",
    "summarize_sequence_trends",
    "write_benchmark_validation_report",
    "validate_faithful_mechanics_transition",
    "write_calibration_report",
    "write_phasefield_comparison_report",
    "write_microstructure_validation_report",
    "write_paper_validation_report",
    "write_elle_phasefield_state",
    "write_figure2_line_validation_html",
    "write_figure2_line_validation_report",
    "write_elle_html_viewer",
    "write_legacy_reference_bundle",
    "write_unode_elle",
]
