"""Public API for the ELLE faithful translation branch.

Faithful solver and parity modules are exported first.
Older phase-field and mixed-runner modules remain importable as archive/prototype
surfaces, but they are not the supported fidelity target.
"""

from .faithful_config import FaithfulSeedData, FaithfulSolverConfig, load_faithful_seed
from .gbm_faithful import (
    FAITHFUL_GBM_DEFAULTS,
    FaithfulGBMSetup,
    build_faithful_gbm_setup,
    run_faithful_gbm_simulation,
)
from .faithful_runtime import (
    initialize_faithful_order_parameters,
    run_faithful_simulation,
    run_faithful_simulation_with_topology,
)
from .faithful_workflow import (
    WorkflowCheckpoint,
    WorkflowCommand,
    WorkflowContext,
    build_faithful_workflow,
    default_workflow_context,
    run_workflow,
    select_checkpoints,
)
from .fft_bridge import (
    FFTMechanicsSnapshot,
    FFTSnapshotPaths,
    LegacyElle2FFTBridgePayload,
    LegacyFFTImportOptions,
    apply_legacy_fft_snapshot_to_mesh_state,
    compare_applied_legacy_fft_snapshot_to_mesh_state,
    build_legacy_elle2fft_bridge_payload,
    build_legacy_fft_bridge_payload,
    compare_legacy_elle2fft_bridge_payload,
    diagnose_legacy_elle2fft_header_sources,
    LegacyFFTBridgePayload,
    load_legacy_elle2fft_bridge_payload,
    load_legacy_fft_snapshot,
    load_legacy_fft_snapshot_sequence,
    write_legacy_elle2fft_bridge_payload,
)
from .mechanics_replay import (
    run_faithful_mechanics_replay,
    validate_faithful_mechanics_outerstep_transition,
    validate_faithful_mechanics_transition,
)
from .legacy_reference import (
    build_legacy_reference_bundle,
    compare_legacy_reference_bundle,
    compare_legacy_reference_snapshot,
    compare_legacy_reference_swept_unode_transition,
    compare_legacy_reference_transition,
    extract_legacy_reference_snapshot,
    extract_legacy_reference_swept_unode_transition,
    extract_legacy_reference_transition,
    load_legacy_reference_bundle,
    write_legacy_reference_bundle,
)
from .legacy_statistics import (
    compare_snapshot_summary_to_legacy_statistics,
    compare_mesh_bookkeeping_to_legacy_old_stats,
    CurrentMeshBookkeepingSummary,
    LegacyAllOutStatisticsRow,
    LegacyLastStatsRow,
    LegacyLastStatsSummary,
    LegacyStatisticsSummaryComparison,
    LegacyOldStatsBookkeepingComparison,
    LegacyOldStatsRow,
    LegacyOldStatsSummary,
    LegacyTmpStatsSummary,
    load_legacy_allout_statistics,
    load_legacy_last_stats_summary,
    load_legacy_old_stats_summary,
    load_legacy_statistics_summary,
    load_legacy_tmpstats_summary,
    summarize_current_mesh_bookkeeping,
)
from .mobility import (
    FaithfulMobilityDB,
    PhaseBoundaryProperty,
    arrhenius_boundary_mobility,
    boundary_segment_mobility,
    caxis_misorientation_degrees,
    default_phase_db_path,
    get_phase_boundary_property,
    load_phase_boundary_db,
    misorientation_mobility_reduction,
)
from .nucleation import NucleationConfig, apply_nucleation_stage
from .recovery import RecoveryConfig, apply_recovery_stage
from .mesh import (
    MeshFeedbackConfig,
    MeshRelaxationConfig,
    apply_mesh_feedback,
    apply_mesh_transport,
    build_mesh_state,
    compute_mesh_motion_velocity,
    couple_mesh_to_order_parameters,
    load_elle_mesh_seed,
    mesh_motion_field,
    rasterize_mesh_labels,
    relax_mesh_state,
)
from .topology import TopologyTracker, run_simulation_with_topology
from .elle_export import extract_flynn_topology, write_unode_elle
from .benchmark_validation import (
    build_benchmark_validation_report,
    evaluate_release_dataset_benchmarks,
    evaluate_rasterized_grain_growth_benchmark,
    evaluate_static_grain_growth_benchmark,
    summarize_elle_label_components,
    summarize_sequence_trends,
    write_benchmark_validation_report,
)
from .figure2_validation import (
    build_figure2_line_validation_report,
    collect_elle_label_area_distributions,
    summarize_elle_label_area_distribution,
    write_figure2_line_validation_html,
    write_figure2_line_validation_report,
)
from .microstructure_validation import (
    collect_elle_microstructure_snapshots,
    compare_elle_microstructure_sequences,
    summarize_elle_microstructure,
    summarize_liu_suckale_datasets,
    write_microstructure_validation_report,
)
from .paper_validation import (
    assess_current_rewrite_against_papers,
    build_paper_validation_report,
    summarize_liu_suckale_paper,
    summarize_liu_suckale_paper_from_text,
    summarize_llorens_structure,
    summarize_llorens_structure_from_text,
    write_paper_validation_report,
)
from .artifacts import dominant_grain_map, save_snapshot_artifacts, snapshot_statistics
from .elle_html_viewer import write_elle_html_viewer
from .elle_visualize import render_elle_file

# Archive / prototype surface kept importable for historical runs.
from .simulation import (
    GrainGrowthConfig,
    initialize_order_parameters,
    load_elle_label_seed,
    run_mesh_only_simulation,
    run_simulation,
)
from .elle_phasefield import (
    EllePhaseFieldConfig,
    EllePhaseFieldTemplate,
    initialize_elle_phasefield,
    load_elle_phasefield_state,
    phasefield_statistics,
    run_elle_phasefield_simulation,
    save_elle_phasefield_artifacts,
    write_elle_phasefield_state,
)
from .phasefield_compare import (
    collect_elle_phasefield_snapshots,
    compare_elle_phasefield_files,
    compare_elle_phasefield_sequences,
    compare_elle_phasefield_states,
    inspect_elle_phasefield_binary,
    run_original_elle_phasefield_sequence,
    run_python_elle_phasefield_sequence,
    write_phasefield_comparison_report,
)
from .calibration import (
    BEST_KNOWN_FINE_FOAM_CALIBRATED_PRESET,
    BEST_KNOWN_FINE_FOAM_PARAMS,
    BEST_KNOWN_FINE_FOAM_PRESET,
    BEST_KNOWN_FINE_FOAM_TRUTHFUL_MESH_PRESET,
    calibrate_fine_foam,
    generate_elle_seeded_candidate_sequence,
    score_existing_calibration_runs,
    write_calibration_report,
)

__all__ = [
    # Faithful public surface
    "FAITHFUL_GBM_DEFAULTS",
    "FaithfulGBMSetup",
    "FaithfulSeedData",
    "FaithfulSolverConfig",
    "build_faithful_gbm_setup",
    "initialize_faithful_order_parameters",
    "load_faithful_seed",
    "run_faithful_gbm_simulation",
    "run_faithful_simulation",
    "run_faithful_simulation_with_topology",
    "WorkflowCheckpoint",
    "WorkflowCommand",
    "WorkflowContext",
    "build_faithful_workflow",
    "default_workflow_context",
    "run_workflow",
    "select_checkpoints",
    "FFTMechanicsSnapshot",
    "FFTSnapshotPaths",
    "LegacyElle2FFTBridgePayload",
    "LegacyFFTBridgePayload",
    "LegacyFFTImportOptions",
    "apply_legacy_fft_snapshot_to_mesh_state",
    "compare_applied_legacy_fft_snapshot_to_mesh_state",
    "build_legacy_elle2fft_bridge_payload",
    "build_legacy_fft_bridge_payload",
    "compare_legacy_elle2fft_bridge_payload",
    "diagnose_legacy_elle2fft_header_sources",
    "load_legacy_fft_snapshot",
    "load_legacy_fft_snapshot_sequence",
    "load_legacy_elle2fft_bridge_payload",
    "write_legacy_elle2fft_bridge_payload",
    "run_faithful_mechanics_replay",
    "validate_faithful_mechanics_transition",
    "build_legacy_reference_bundle",
    "compare_legacy_reference_bundle",
    "compare_legacy_reference_snapshot",
    "compare_legacy_reference_swept_unode_transition",
    "compare_legacy_reference_transition",
    "extract_legacy_reference_snapshot",
    "extract_legacy_reference_swept_unode_transition",
    "extract_legacy_reference_transition",
    "load_legacy_reference_bundle",
    "write_legacy_reference_bundle",
    "CurrentMeshBookkeepingSummary",
    "LegacyAllOutStatisticsRow",
    "LegacyLastStatsRow",
    "LegacyLastStatsSummary",
    "LegacyStatisticsSummaryComparison",
    "LegacyOldStatsBookkeepingComparison",
    "LegacyOldStatsRow",
    "LegacyOldStatsSummary",
    "LegacyTmpStatsSummary",
    "compare_snapshot_summary_to_legacy_statistics",
    "compare_mesh_bookkeeping_to_legacy_old_stats",
    "load_legacy_allout_statistics",
    "load_legacy_last_stats_summary",
    "load_legacy_old_stats_summary",
    "load_legacy_statistics_summary",
    "load_legacy_tmpstats_summary",
    "summarize_current_mesh_bookkeeping",
    "FaithfulMobilityDB",
    "PhaseBoundaryProperty",
    "arrhenius_boundary_mobility",
    "boundary_segment_mobility",
    "caxis_misorientation_degrees",
    "default_phase_db_path",
    "get_phase_boundary_property",
    "load_phase_boundary_db",
    "misorientation_mobility_reduction",
    "NucleationConfig",
    "apply_nucleation_stage",
    "RecoveryConfig",
    "apply_recovery_stage",
    "MeshFeedbackConfig",
    "MeshRelaxationConfig",
    "apply_mesh_feedback",
    "apply_mesh_transport",
    "build_mesh_state",
    "compute_mesh_motion_velocity",
    "couple_mesh_to_order_parameters",
    "load_elle_mesh_seed",
    "mesh_motion_field",
    "rasterize_mesh_labels",
    "relax_mesh_state",
    "TopologyTracker",
    "run_simulation_with_topology",
    "extract_flynn_topology",
    "write_unode_elle",
    # Validation and inspection
    "build_benchmark_validation_report",
    "evaluate_release_dataset_benchmarks",
    "evaluate_rasterized_grain_growth_benchmark",
    "evaluate_static_grain_growth_benchmark",
    "summarize_elle_label_components",
    "summarize_sequence_trends",
    "write_benchmark_validation_report",
    "build_figure2_line_validation_report",
    "collect_elle_label_area_distributions",
    "summarize_elle_label_area_distribution",
    "write_figure2_line_validation_html",
    "write_figure2_line_validation_report",
    "collect_elle_microstructure_snapshots",
    "compare_elle_microstructure_sequences",
    "summarize_elle_microstructure",
    "summarize_liu_suckale_datasets",
    "write_microstructure_validation_report",
    "assess_current_rewrite_against_papers",
    "build_paper_validation_report",
    "summarize_liu_suckale_paper",
    "summarize_liu_suckale_paper_from_text",
    "summarize_llorens_structure",
    "summarize_llorens_structure_from_text",
    "write_paper_validation_report",
    "dominant_grain_map",
    "save_snapshot_artifacts",
    "snapshot_statistics",
    "write_elle_html_viewer",
    "render_elle_file",
    # Archive / prototype surface
    "GrainGrowthConfig",
    "initialize_order_parameters",
    "load_elle_label_seed",
    "run_mesh_only_simulation",
    "run_simulation",
    "EllePhaseFieldConfig",
    "EllePhaseFieldTemplate",
    "initialize_elle_phasefield",
    "load_elle_phasefield_state",
    "phasefield_statistics",
    "run_elle_phasefield_simulation",
    "save_elle_phasefield_artifacts",
    "write_elle_phasefield_state",
    "collect_elle_phasefield_snapshots",
    "compare_elle_phasefield_files",
    "compare_elle_phasefield_sequences",
    "compare_elle_phasefield_states",
    "inspect_elle_phasefield_binary",
    "run_original_elle_phasefield_sequence",
    "run_python_elle_phasefield_sequence",
    "write_phasefield_comparison_report",
    "BEST_KNOWN_FINE_FOAM_CALIBRATED_PRESET",
    "BEST_KNOWN_FINE_FOAM_PARAMS",
    "BEST_KNOWN_FINE_FOAM_PRESET",
    "BEST_KNOWN_FINE_FOAM_TRUTHFUL_MESH_PRESET",
    "calibrate_fine_foam",
    "generate_elle_seeded_candidate_sequence",
    "score_existing_calibration_runs",
    "write_calibration_report",
]
